require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GenotypesController do

  # This should return the minimal set of attributes required to create a valid
  # Genotype. As you add validations to Genotype, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "genes" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GenotypesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all genotypes as @genotypes" do
      genotype = Genotype.create! valid_attributes
      get :index, {}, valid_session
      assigns(:genotypes).should eq([genotype])
    end
  end

  describe "GET show" do
    it "assigns the requested genotype as @genotype" do
      genotype = Genotype.create! valid_attributes
      get :show, {:id => genotype.to_param}, valid_session
      assigns(:genotype).should eq(genotype)
    end
  end

  describe "GET new" do
    it "assigns a new genotype as @genotype" do
      get :new, {}, valid_session
      assigns(:genotype).should be_a_new(Genotype)
    end
  end

  describe "GET edit" do
    it "assigns the requested genotype as @genotype" do
      genotype = Genotype.create! valid_attributes
      get :edit, {:id => genotype.to_param}, valid_session
      assigns(:genotype).should eq(genotype)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Genotype" do
        expect {
          post :create, {:genotype => valid_attributes}, valid_session
        }.to change(Genotype, :count).by(1)
      end

      it "assigns a newly created genotype as @genotype" do
        post :create, {:genotype => valid_attributes}, valid_session
        assigns(:genotype).should be_a(Genotype)
        assigns(:genotype).should be_persisted
      end

      it "redirects to the created genotype" do
        post :create, {:genotype => valid_attributes}, valid_session
        response.should redirect_to(Genotype.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved genotype as @genotype" do
        # Trigger the behavior that occurs when invalid params are submitted
        Genotype.any_instance.stub(:save).and_return(false)
        post :create, {:genotype => { "genes" => "invalid value" }}, valid_session
        assigns(:genotype).should be_a_new(Genotype)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Genotype.any_instance.stub(:save).and_return(false)
        post :create, {:genotype => { "genes" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested genotype" do
        genotype = Genotype.create! valid_attributes
        # Assuming there are no other genotypes in the database, this
        # specifies that the Genotype created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Genotype.any_instance.should_receive(:update_attributes).with({ "genes" => "" })
        put :update, {:id => genotype.to_param, :genotype => { "genes" => "" }}, valid_session
      end

      it "assigns the requested genotype as @genotype" do
        genotype = Genotype.create! valid_attributes
        put :update, {:id => genotype.to_param, :genotype => valid_attributes}, valid_session
        assigns(:genotype).should eq(genotype)
      end

      it "redirects to the genotype" do
        genotype = Genotype.create! valid_attributes
        put :update, {:id => genotype.to_param, :genotype => valid_attributes}, valid_session
        response.should redirect_to(genotype)
      end
    end

    describe "with invalid params" do
      it "assigns the genotype as @genotype" do
        genotype = Genotype.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Genotype.any_instance.stub(:save).and_return(false)
        put :update, {:id => genotype.to_param, :genotype => { "genes" => "invalid value" }}, valid_session
        assigns(:genotype).should eq(genotype)
      end

      it "re-renders the 'edit' template" do
        genotype = Genotype.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Genotype.any_instance.stub(:save).and_return(false)
        put :update, {:id => genotype.to_param, :genotype => { "genes" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested genotype" do
      genotype = Genotype.create! valid_attributes
      expect {
        delete :destroy, {:id => genotype.to_param}, valid_session
      }.to change(Genotype, :count).by(-1)
    end

    it "redirects to the genotypes list" do
      genotype = Genotype.create! valid_attributes
      delete :destroy, {:id => genotype.to_param}, valid_session
      response.should redirect_to(genotypes_url)
    end
  end

end
